#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l vmem=8gb
#PBS -l walltime=00:10:00

set -e

# Bypass
MASK=$(jq -r '.mask' config.json)
echo '{"errors": [], "warnings": []}' > product.json
mkdir -p output
cp $MASK output/mask.nii.gz
